name: Email Notification

on:
    push:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 14

            - name: Install dependencies
              working-directory: appartement-backend
              run: npm install

            - name: Run tests
              working-directory: appartement-backend
              run: npm test

    send-email:
        needs: run-tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 14

            - name: Install dependencies
              working-directory: appartement-backend
              run: npm install nodemailer

            - name: Run mail.js
              working-directory: appartement-backend
              run: node mail.js
